# Generated by Django 3.2.9 on 2021-11-24 07:21

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211117_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_cover',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, upload_to='course/cover', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '付费购买'), (1, '会员专享'), (2, '学位课程')], default=0, verbose_name='付费类型'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='课程原价'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_list', to='courses.teacher', verbose_name='授课老师'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='lesson_link',
            field=models.CharField(blank=True, help_text='若是video，填视频地址或者视频id，若是文档，填文档地址', max_length=255, null=True, verbose_name='课程链接'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=stdimage.models.StdImageField(null=True, upload_to='teacher', verbose_name='讲师头像'),
        ),
    ]
