# Generated by Django 3.2.9 on 2021-11-24 09:27

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211124_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 11, 24, 9, 27, 2, 80183, tzinfo=utc), verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2021, 11, 24, 9, 27, 2, 80217, tzinfo=utc), verbose_name='结束时间')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='活动介绍')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '优惠活动',
                'verbose_name_plural': '优惠活动',
                'db_table': 'fg_activity',
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.CharField(blank=True, max_length=250, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '优惠类型',
                'verbose_name_plural': '优惠类型',
                'db_table': 'fg_discount_type',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('condition', models.IntegerField(blank=True, default=0, help_text='设置优惠的价格条件，如果不填或0则没有优惠门槛', verbose_name='满足优惠的价格条件')),
                ('sale', models.TextField(help_text='\n    0表示免费；<br>\n    *号开头表示折扣价，例如填写*0.82，则表示八二折；<br>\n    -号开头表示减免价，例如填写-100，则表示减免100；<br>\n    ', verbose_name='优惠公式')),
                ('discount_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='discount_list', to='courses.discounttype', verbose_name='优惠类型')),
            ],
            options={
                'verbose_name': '优惠公式',
                'verbose_name_plural': '优惠公式',
                'db_table': 'fg_discount',
            },
        ),
        migrations.CreateModel(
            name='CourseActivityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('activity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='courses.activity', verbose_name='活动')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='courses.course', verbose_name='课程')),
                ('discount', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='courses.discount', verbose_name='优惠')),
            ],
            options={
                'verbose_name': '课程参与活动的价格表',
                'verbose_name_plural': '课程参与活动的价格表',
                'db_table': 'fg_course_activity_price',
            },
        ),
    ]
