# Generated by Django 3.2.9 on 2021-11-26 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_activity_courseactivityprice_discount_discounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 16, 53, 41, 813746), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 16, 53, 41, 813714), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '实战课程'), (1, '会员专享'), (2, '学位课程')], default=0, verbose_name='付费类型'),
        ),
    ]
