# Generated by Django 3.2.9 on 2021-11-29 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20211126_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 14, 12, 16, 152922), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 14, 12, 16, 152880), verbose_name='开始时间'),
        ),
    ]
