# Generated by Django 3.2.9 on 2021-11-24 07:21

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, default='http://api.fuguang.cn:8000/uploads/avatar/2021/avatar.thumb_800x800_lUbXFXP.thumb_50x50.jpg', null=True, upload_to='avatar/%Y', verbose_name='个人头像'),
        ),
    ]
